# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

before:
  hooks:
    - go mod tidy
builds:
  - id: kube-startup-cpu-boost
    main: ./cmd
    binary: manager 
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - "-s -w"
    goos:
      - linux
    goarch:
      - amd64
    hooks:
      pre:
        - cmd: make manifests generate 
      post:
        - cmd: make release IMG=ghcr.io/google/{{ .ProjectName }}:{{ .Tag }} MANIFESTS=manifests.yaml
dockers:
  - goos: linux
    goarch: amd64
    dockerfile: goreleaser.dockerfile
    image_templates:
      - "ghcr.io/google/{{ .ProjectName }}:latest"
      - "ghcr.io/google/{{ .ProjectName }}:{{ .Tag }}" 
      - "ghcr.io/google/{{ .ProjectName }}:{{ .ShortCommit }}" 
archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - kube-startup-cpu-boost
    files:
      - LICENSE*
      - README*
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256
release:
  # If you want to manually examine the release before its live, uncomment this line:
  # draft: true
  extra_files:
    - glob: ./manifests.yaml
changelog:
  skip: true