apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: secret
    app.kubernetes.io/instance: webhook-secret
    app.kubernetes.io/component: internal-cert
    app.kubernetes.io/created-by: kube-startup-cpu-boost
    app.kubernetes.io/part-of: kube-startup-cpu-boost
    app.kubernetes.io/managed-by: kustomize
  name: webhook-secret
