# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: spring-demo-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: spring-demo-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spring-demo-app
    spec:
      serviceAccountName: spring-demo-app
      containers:
      - name: spring-demo-app
        image: ghcr.io/google/spring-demo-app:latest
        args:
        - --spring.config.location=file:/config/application.yaml
        env:
        - name: JAVA_OPTS
          value: -XX:MaxRAMPercentage=75
        volumeMounts:
        - name: spring-demo-app-config
          mountPath: /config
        ports:
        - name: http
          containerPort: 8080
        startupProbe:
          periodSeconds: 2
          failureThreshold: 60
          httpGet:
            path: /actuator/health
            port: http
            scheme: HTTP
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: http
            scheme: HTTP
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 512Mi
      volumes:
      - name: spring-demo-app-config
        configMap:
          name: spring-demo-app-config
---
apiVersion: v1
kind: Service
metadata:
  name: spring-demo-app
spec:
  selector:
    app.kubernetes.io/name: spring-demo-app
  ports:
  - port: 8080
    targetPort: http
