apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kube-startup-cpu-boost-internal-cert-role
  labels:
    app.kubernetes.io/component: internal-cert
    app.kubernetes.io/created-by: kube-startup-cpu-boost
    app.kubernetes.io/part-of: kube-startup-cpu-boost
  {{- include "kube-startup-cpu-boost.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kube-startup-cpu-boost-internal-cert-rolebinding
  labels:
    app.kubernetes.io/component: internal-cert
    app.kubernetes.io/created-by: kube-startup-cpu-boost
    app.kubernetes.io/part-of: kube-startup-cpu-boost
  {{- include "kube-startup-cpu-boost.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kube-startup-cpu-boost-internal-cert-role
subjects:
- kind: ServiceAccount
  name: kube-startup-cpu-boost-controller-manager
  namespace: '{{ .Release.Namespace }}'
