apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "kube-startup-cpu-boost.fullname" . }}-mutating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "kube-startup-cpu-boost.fullname" . }}-
  labels:
  {{- include "kube-startup-cpu-boost.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: kube-startup-cpu-boost-webhook-service
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-v1-pod
  failurePolicy: Ignore
  name: cpuboost.autoscaling.x-k8s.io
  namespaceSelector:
    matchExpressions:
    - key: app.kubernetes.io/part-of
      operator: NotIn
      values:
      - kube-startup-cpu-boost
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  sideEffects: None
  timeoutSeconds: 2
