// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/google/kube-startup-cpu-boost/internal/boost (interfaces: Manager)
//
// Generated by this command:
//
//	mockgen -package mock --copyright_file hack/boilerplate.go.txt --destination internal/mock/boost_manager.go github.com/google/kube-startup-cpu-boost/internal/boost Manager
//

package mock

import (
	context "context"
	reflect "reflect"

	boost "github.com/google/kube-startup-cpu-boost/internal/boost"
	gomock "go.uber.org/mock/gomock"
	v1 "k8s.io/api/core/v1"
	reconcile "sigs.k8s.io/controller-runtime/pkg/reconcile"
)

// MockManager is a mock of Manager interface.
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance.
func NewMockManager(ctrl *gomock.Controller) *MockManager {
	mock := &MockManager{ctrl: ctrl}
	mock.recorder = &MockManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	return m.recorder
}

// AddStartupCPUBoost mocks base method.
func (m *MockManager) AddStartupCPUBoost(arg0 context.Context, arg1 boost.StartupCPUBoost) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddStartupCPUBoost", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddStartupCPUBoost indicates an expected call of AddStartupCPUBoost.
func (mr *MockManagerMockRecorder) AddStartupCPUBoost(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddStartupCPUBoost", reflect.TypeOf((*MockManager)(nil).AddStartupCPUBoost), arg0, arg1)
}

// RemoveStartupCPUBoost mocks base method.
func (m *MockManager) RemoveStartupCPUBoost(arg0 context.Context, arg1, arg2 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveStartupCPUBoost", arg0, arg1, arg2)
}

// RemoveStartupCPUBoost indicates an expected call of RemoveStartupCPUBoost.
func (mr *MockManagerMockRecorder) RemoveStartupCPUBoost(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveStartupCPUBoost", reflect.TypeOf((*MockManager)(nil).RemoveStartupCPUBoost), arg0, arg1, arg2)
}

// SetStartupCPUBoostReconciler mocks base method.
func (m *MockManager) SetStartupCPUBoostReconciler(arg0 reconcile.Reconciler) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetStartupCPUBoostReconciler", arg0)
}

// SetStartupCPUBoostReconciler indicates an expected call of SetStartupCPUBoostReconciler.
func (mr *MockManagerMockRecorder) SetStartupCPUBoostReconciler(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStartupCPUBoostReconciler", reflect.TypeOf((*MockManager)(nil).SetStartupCPUBoostReconciler), arg0)
}

// Start mocks base method.
func (m *MockManager) Start(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockManagerMockRecorder) Start(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockManager)(nil).Start), arg0)
}

// StartupCPUBoost mocks base method.
func (m *MockManager) StartupCPUBoost(arg0, arg1 string) (boost.StartupCPUBoost, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartupCPUBoost", arg0, arg1)
	ret0, _ := ret[0].(boost.StartupCPUBoost)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// StartupCPUBoost indicates an expected call of StartupCPUBoost.
func (mr *MockManagerMockRecorder) StartupCPUBoost(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartupCPUBoost", reflect.TypeOf((*MockManager)(nil).StartupCPUBoost), arg0, arg1)
}

// StartupCPUBoostForPod mocks base method.
func (m *MockManager) StartupCPUBoostForPod(arg0 context.Context, arg1 *v1.Pod) (boost.StartupCPUBoost, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartupCPUBoostForPod", arg0, arg1)
	ret0, _ := ret[0].(boost.StartupCPUBoost)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// StartupCPUBoostForPod indicates an expected call of StartupCPUBoostForPod.
func (mr *MockManagerMockRecorder) StartupCPUBoostForPod(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartupCPUBoostForPod", reflect.TypeOf((*MockManager)(nil).StartupCPUBoostForPod), arg0, arg1)
}
